IMAGE_SIZE     = 448
CELL_SIZE      = 7
BOXES_PER_CELL = 2
LAMBDA_COORD   = 5
LAMBDA_NOOBJ   = 0.5
NMS_THREHOLDS = 0.2

TRAIN_BATCHSIZE = 32

DATA_PATH ='D:\PRIV\Mydata\DATA'
CACHE_PATH = 'D:\PRIV\Mydata\DATA'

BATCH_SIZE = 32
IMAGE_SIZE = 448

FLIPPED = False

CLASSES = ['tyrannosaurus']
